version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_net

  metrics_server:
    build: C:/airfloww/dags/Scripts/promotheus_exporter
    container_name: metrics_server
    ports:
      - "9100:9100"
      - "9200:9200"
    networks:
      - monitoring_net

networks:
  monitoring_net:
    driver: bridge